### ISSUE TITLE
Feature request: "natural" looping

### ISSUE THREAD

**Issue by juef17** [ExoticMatter/ImoSPC#1]
Greetings,

It seems like ImoSPC doesn't yet have a way to let the tracks play indefinitely if they have a looping point. I feel like it would be a great feature to add, especially if it can be toggled on and off.

I would gladly try and do it myself, but what I've done so far is very hack-ish and definitely not as high quality code as ImoSPC is.

Thank you!

**Comment by ExoticMatter** [comment]
Added the function [ImoSPC.setRepeat](https://github.com/ExoticMatter/ImoSPC/wiki/API-Reference#function-imospcsetrepeatrepeat--boolean).

**Comment by juef17** [comment]
This is great, thank you very much! My project using this is almost done, I'll let you know when you can check it out. Thanks again for adding this feature!
